### ISSUE TITLE
Using difft with magit

### ISSUE THREAD

**Issue by AeroNotix** [Wilfred/difftastic#235] opened 2022-04-04 12:33 UTC
Hi,

How do I get magit to use the same highlighting that difft uses on the command line?

I've set difft as the difftool in my config but magit diffs are still rendered in the default way.

**Comment by AeroNotix** [comment] 2022-04-04 12:34
https://emacs.stackexchange.com/questions/47980/how-to-ask-magit-to-use-external-diff-and-merge-tools I came across this and perhaps it is magit which doesn't support this.

**Comment by petr-tik** [comment] 2022-04-05 22:04
There is a package that configures magit to use delta, so it should be possible to integrate difft with magit with a package

https://github.com/dandavison/magit-delta/

**Comment by Wilfred** [comment] 2022-04-14 06:57
Duplicate of #251.

**Closed by Wilfred** 2022-04-14 06:57 UTC
