### ISSUE TITLE
files::tests::test_gzip_is_binary failure in 0.43.0

### ISSUE THREAD

**Issue by AMDmi3** [Wilfred/difftastic#479] opened 2023-02-03 13:15 UTC
When updating FreeBSD port of difftastic to 0.43.0:

```
running 118 tests
test diff::dijkstra::tests::atom_after_empty_list ... ok
test diff::dijkstra::tests::atom_after_novel_list_contiguous ... ok
test diff::dijkstra::tests::mark_syntax_different_atoms ... ok
test diff::dijkstra::tests::mark_syntax_equal_atoms ... ok
test diff::dijkstra::tests::prefer_atoms_same_line ... ok
test diff::dijkstra::tests::prefer_children_same_line ... ok
test diff::dijkstra::tests::repeated_atoms ... ok
test diff::dijkstra::tests::replace_comment_prefer_most_similar ... ok
test diff::dijkstra::tests::replace_similar_comment ... ok
test diff::dijkstra::tests::replace_very_different_comment ... ok
test diff::myers_diff::tests::test_slice_by_hash_different_items ... ok
test diff::myers_diff::tests::test_slice_by_hash_same_items ... ok
test diff::myers_diff::tests::test_slice_different_items ... ok
test diff::myers_diff::tests::test_slice_same_items ... ok
test diff::myers_diff::tests::test_slice_unique_different_items ... ok
test diff::myers_diff::tests::test_slice_unique_same_items ... ok
test diff::sliders::tests::test_slider_at_end ... ok
test diff::sliders::tests::test_slider_at_start ... ok
test diff::sliders::tests::test_slider_partially_unchanged ... ok
test diff::sliders::tests::test_slider_two_steps ... ok
test diff::unchanged::tests::test_count_common_unique ... ok
test diff::unchanged::tests::test_shrink_unchanged_at_end ... ok
test diff::unchanged::tests::test_shrink_unchanged_at_start ... ok
test diff::unchanged::tests::test_shrink_unchanged_nested ... ok
test diff::unchanged::tests::test_similar_ignore_delimiter ... ok
test diff::unchanged::tests::test_similar_with_common_grandchildren ... ok
test diff::unchanged::tests::test_split_mostly_unchanged_toplevel ... ok
test diff::unchanged::tests::test_split_preserves_outer_delimiters ... ok
test diff::unchanged::tests::test_split_unchanged_middle ... ok
test diff::unchanged::tests::test_split_unchanged_multiple ... ok
test diff::dijkstra::tests::extra_atom_lhs ... ok
test diff::unchanged::tests::test_split_unchanged_outer_delimiter ... ok
test diff::unchanged::tests::test_split_unchanged_toplevel_at_end ... ok
test display::context::tests::test_all_lines ... ok
test diff::unchanged::tests::test_split_unchanged_toplevel_at_start ... ok
test display::context::tests::test_all_matched_lines ... ok
test display::context::tests::test_calculate_before_context ... ok
test display::context::tests::test_compact_gaps_with_larger_gap ... ok
test display::context::tests::test_match_blanks_between ... ok
test display::context::tests::test_match_preceding_blanks ... ok
test display::context::tests::test_match_preceding_blanks_first_pair ... ok
test display::context::tests::test_matched_lines_blank_at_ends ... ok
test display::context::tests::test_matched_lines_novel_on_same_line ... ok
test display::context::tests::test_compact_gaps ... ok
test display::context::tests::test_pad_after_when_line_exceeds_max ... ok
test display::hunks::tests::test_matched_lines_for_hunk ... ok
test display::hunks::tests::test_matched_lines_for_hunk_misaligned ... ok
test diff::dijkstra::tests::identical_atoms ... ok
test display::hunks::tests::test_matched_pos_to_hunks ... ok
test display::hunks::tests::test_sorted_novel_positions_simple ... ok
test display::side_by_side::tests::test_display_single_column ... ok
test display::side_by_side::tests::test_format_missing_line_num ... ok
test display::side_by_side::tests::test_format_missing_line_num_at_end ... ok
test display::side_by_side::tests::test_width_calculations ... ok
test display::style::tests::split_string_cjk ... ok
test display::style::tests::split_string_cjk2 ... ok
test display::side_by_side::tests::test_display_hunks ... ok
test display::style::tests::split_string_simple ... ok
test display::style::tests::split_string_unicode ... ok
test display::style::tests::test_split_and_apply ... ok
test display::style::tests::test_split_and_apply_gap_between_styles_on_wrap_boundary ... ok
test display::style::tests::test_split_and_apply_missing ... ok
test display::style::tests::test_split_and_apply_trailing_text ... ok
test display::style::tests::test_split_and_apply_trailing_text_newline ... ok
test display::style::tests::test_combining_char ... ok
test files::tests::test_gzip_is_binary ... FAILED
test files::tests::test_png_bytes_are_binary ... ok
test line_parser::tests::test_novel_lhs_trailing_newlines ... ok
test line_parser::tests::test_positions_no_changes ... ok
test line_parser::tests::test_positions_novel_lhs ... ok
test line_parser::tests::test_positions_whitespace_is_change ... ok
test line_parser::tests::test_split_newlines ... ok
test lines::tests::codepoint_len_non_ascii ... ok
test files::tests::test_plaintext_is_text ... ok
test lines::tests::empty_str_max_line ... ok
test line_parser::tests::test_no_changes_trailing_newlines ... ok
test lines::tests::from_offsets_first_line ... ok
test lines::tests::from_offsets_split_over_multiple_lines ... ok
test lines::tests::str_max_line ... ok
test lines::tests::str_max_line_extra_trailing_newline ... ok
test lines::tests::str_max_line_trailing_newline ... ok
test lines::tests::test_is_all_whiteapce ... ok
test lines::tests::test_split_line_empty ... ok
test lines::tests::test_split_line_single ... ok
test lines::tests::test_split_line_with_crlf ... ok
test lines::tests::test_split_line_with_newline ... ok
test lines::tests::test_split_line_with_trailing_newline ... ok
test lines::tests::from_offsets_first_char ... ok
test options::tests::test_app ... ok
test lines::tests::from_offsets_relative_to ... ok
test parse::guess_language::tests::test_guess_by_emacs_mode ... ok
test parse::guess_language::tests::test_guess_by_emacs_mode_shorthand ... ok
test parse::guess_language::tests::test_guess_by_emacs_mode_shorthand_no_spaces ... ok
test options::tests::test_detect_display_width ... ok
test parse::guess_language::tests::test_guess_by_emacs_mode_second_line ... ok
test parse::guess_language::tests::test_guess_by_extension ... ok
test parse::guess_language::tests::test_guess_by_env_shebang ... ok
test parse::guess_language::tests::test_guess_by_whole_name ... ok
test parse::guess_language::tests::test_guess_unknown ... ok
test parse::syntax::tests::test_atom_equality_ignores_highlighting ... ok
test parse::syntax::tests::test_comment_and_atom_differ ... ok
test parse::syntax::tests::test_flatten_trivial_list ... ok
test parse::syntax::tests::test_ignore_empty_atoms ... ok
test parse::syntax::tests::test_multiline_comment_ignores_leading_whitespace ... ok
test parse::syntax::tests::test_new_atom_truncates_carriage_return ... ok
test parse::syntax::tests::test_split_comment_words_basic ... ok
test parse::syntax::tests::test_split_words ... ok
test parse::syntax::tests::test_split_words_punctuations ... ok
test parse::syntax::tests::test_split_words_single_unicode ... ok
test parse::syntax::tests::test_split_words_single_unicode_not_alphabetic ... ok
test parse::guess_language::tests::test_guess_by_shebang ... ok
test parse::syntax::tests::test_split_words_treats_newline_separately ... ok
test parse::syntax::tests::test_split_words_unicode ... ok
test parse::tree_sitter_parser::tests::test_parse ... ok
test parse::tree_sitter_parser::tests::test_parse_empty_file ... ok
test parse::tree_sitter_parser::tests::test_subtrees ... ok
test display::context::tests::test_merge_in_opposite_lines ... ok
test tests::test_diff_identical_content ... ok

failures:

---- files::tests::test_gzip_is_binary stdout ----
thread 'files::tests::test_gzip_is_binary' panicked at 'assertion failed: `(left == right)`
  left: `Text("謟\u{8}뀺掑\u{300}躋˥䐀棒Ͱ\0")`,
 right: `Binary`', src/files.rs:299:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    files::tests::test_gzip_is_binary

test result: FAILED. 117 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.05s
```

**Comment by Wilfred** [comment] 2023-02-04 18:58
Duplicate of #478, thanks for the report!

**Closed by Wilfred** 2023-02-04 18:58 UTC
