### ISSUE TITLE
Syntactic change in Makefile mislabed as no syntactic change

### ISSUE THREAD

**Issue by maribu** [Wilfred/difftastic#405] opened 2022-10-12 11:13 UTC
```
~ $ cat a/Makefile 
CFLAGS += \
  -DRIOT_FLASH_SIZE=$(FLASH_SIZE) \
  #
~ $ cat b/Makefile 
CFLAGS += \
  -DRIOT_FLASH_SIZE=$(FLASH_SIZE) \
  -specs=picolibc.specs \
  #
~ $ diff a b
--- a/Makefile
+++ b/Makefile
@@ -1,3 +1,4 @@
 CFLAGS += \
   -DRIOT_FLASH_SIZE=$(FLASH_SIZE) \
+  -specs=picolibc.specs \
   #
~ $ difft a b
Makefile --- Make
No syntactic changes.
```

It seems that the use of variables (`$(FLASH_SIZE)`) is confusing difftastic. If replaced the `$(FLASH_SIZE)` with a numeric constant, the difference is detected as being of syntactic difference.

**Comment by Wilfred** [comment] 2022-10-12 20:20
Duplicate of #350.

**Closed by Wilfred** 2022-10-12 20:20 UTC
