### ISSUE TITLE
[Feature Request] Provide better diff for string syntax

### ISSUE THREAD

**Issue by QuarticCat** [Wilfred/difftastic#403] opened 2022-10-08 10:49 UTC
Currently, even a small change in a string will cause difftastic thinking that they are totally different. For example, in the following example, the only change is `KB -> MB`:

![image](https://user-images.githubusercontent.com/70888415/194703637-6570838d-13cd-4ee2-98d2-effd30fa21a7.png)

If we can detect such a situation and run a cheaper diff algorithm like some word-based or char-based algorithm on it, and mark the difference (e.g., make them bold), the diff result will be better. This can be optional.

**Comment by sesse** [comment] 2022-10-10 12:22
A variant of this is in #382.

**Comment by sesse** [comment] 2022-10-10 12:24
Also #376, #178, #312.

**Comment by Wilfred** [comment] 2022-10-28 05:25
I think this is a duplicate of #178. I agree it would be really nice to do better here.

**Closed by Wilfred** 2022-10-28 05:25 UTC
