### ISSUE TITLE
Large invalid JSON coredumps with `munmap_chunk(): invalid pointer` 

### ISSUE THREAD

**Issue by gthb** [Wilfred/difftastic#570] opened 2023-09-08 12:24 UTC
Repro instructions:

```sh
git clone git@github.com:slackapi/slack-github-action.git
cd slack-github-action
difft --override '*:json' <(jq -C . package-lock.json) <(jq -C . package.json)
```

(The particular repo I'm fetching there is not relevant, it's just to get a fairly large blob of JSON that's open-source, and not all blobs of JSON do reproduce this. Didn't copy the JSON inline here because it is large, and I think it needs to be large.)

That outputs:
```
munmap_chunk(): invalid pointer
[1]    3879943 IOT instruction (core dumped)  difft --override '*:json' <(jq -C . package-lock.json) <(jq -C . package.json
```

Of course `jq -C` forces color output, so what Difftastic is receiving is not really JSON, it is JSON mixed with terminal escape codes for colors.

But whatever should happen in that case, it isn't the above. :) So I'm reporting error handling going awry, not really something that should “work”.

Discovered because I was intending to diff JSON produced by `<(jq .someProperty somefile.json)` and had forgotten that my `jq` was tricked out like this in my shell to always produce color:

```sh
jqjq() {
    # -F tell less exit if output content can be displayed on one screen
    jq -C "$@" | less -FR
}
alias jq=jqjq
```

I _should_ be slapped for that, of course, but ideally I should be slapped with some other error message. :)

Reproduces with Difftastic 0.51.1 on my Arch Linux machine:
* `uname -a`: `Linux scrarch 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux`
* Installed difftastic 0.51.1-3 with Pacman

... and on my Mac (notably it does not always reproduce on both my Mac and my Linux machine with the same files, but I did find those slack-github-action files which reproduce it on both):
* macOS 13.5.1 (22G90)
* `uname -a`: Darwin skryabin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
* Installed difftastic 0.51.1 with Homebrew

**Comment by Wilfred** [comment] 2023-09-08 15:19
Thanks for the report. This is almost certainly an upstream issue in https://github.com/tree-sitter/tree-sitter-json, but I'll try to get a repro for upstream.

**Comment by karlding** [comment] 2024-01-27 11:58
I ran into a similar crash which I think is the same issue as this? I say this because the same change that fixed my issue also seems to have fixed a crash that occurs when following the reproduction steps in this issue.

Using the reproduction instructions provided in the first comment:

```
$ git clone git@github.com:slackapi/slack-github-action.git
$ cd slack-github-action
$ jq -C . package-lock.json | tee bad.json
```

Then from the `difftastic` repo:

```
$ git log --oneline -n1
2d61aefb8 (HEAD -> master, upstream/master, upstream/HEAD) Fix tab replacement in single-column display

$ cargo build --locked
(...)

$ ./target/difft --dump-ts bad.json
(...)
free(): invalid size
Aborted
```

I first wanted to check if this was fixed upstream, so I tried updating the vendored JSON parser.

```
$ git subtree pull --prefix=vendored_parsers/tree-sitter-json git@github.com:tree-sitter/tree-sitter-json.git master

$ ./target/difft --dump-ts bad.json
(...)
free(): invalid size
Aborted
```

This didn’t change anything, so I looked at the backtrace in gdb and noticed that the backtrace was from tree-sitter when doing a `drop`.

```
$ gdb --args ./target/debug/difft --dump-ts bad.json
>>> r
>>> bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737348184256) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737348184256) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737348184256, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7a99476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7a7f7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7ae0676 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7c32b77 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7af7cfc in malloc_printerr (str=str@entry=0x7ffff7c3075c "free(): invalid size") at ./malloc/malloc.c:5664
#7  0x00007ffff7af9a54 in _int_free (av=<optimized out>, p=0x7ffff7874000, have_lock=0) at ./malloc/malloc.c:4443
#8  0x00007ffff7afc453 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x0000555555fa9516 in ts_subtree_release (pool=0x7fffffffcab0, self=...) at src/./subtree.c:609
#10 0x0000555555faaec1 in ts_tree_delete (self=0x55555abedad0) at src/./tree.c:31
#11 0x0000555555f75e82 in tree_sitter::{impl#6}::drop (self=0x7fffffffd178) at binding_rust/lib.rs:776
#12 0x00005555557175db in core::ptr::drop_in_place<tree_sitter::Tree> () at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ptr/mod.rs:487
#13 0x00005555556c4371 in difft::main () at src/main.rs:128
```

This didn’t seem like an issue with the `tree-sitter-json` parser but potentially in the bindings or library, so I updated the `tree-sitter crate` from `0.20.9` to `0.20.10`.

```
$ cargo update --package tree-sitter

$ git diff Cargo.lock
diff --git i/Cargo.lock w/Cargo.lock
index d249ecaae..f0bca647b 100644
--- i/Cargo.lock
+++ w/Cargo.lock
@@ -1053,9 +1053,9 @@ dependencies = [

 [[package]]
 name = "tree-sitter"
-version = "0.20.9"
+version = "0.20.10"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "d4423c784fe11398ca91e505cdc71356b07b1a924fc8735cfab5333afe3e18bc"
+checksum = "e747b1f9b7b931ed39a548c1fae149101497de3c1fc8d9e18c62c1a66c683d3d"
 dependencies = [
  "cc",
  "regex",

$ cargo build --locked

$ ./target/debug/difft --dump-ts bad.json
$ echo $?
0
```

This seems to fix both the issue originally reported as well as the issue I ran into. Thus, it seems like this is an issue in the upstream `tree-sitter` crate that has already been fixed, and was not an issue in the `tree-sitter-json` crate.

Now for some reason, the tags in the `tree-sitter` repository don’t match the crate versions on crates.io, so it wasn’t really obvious to me how to correlate the versions released on crates.io with the release version tags in the Git repository. I ended up checking the `lib/Cargo.toml` file for when the version bumps occurred.

```
$ git log --oneline -S '0.20.9' lib/Cargo.toml
811bc825 lib: 0.20.10
2be51abc Bump library versions
```

I then set up a local copy to bisect the upstream `tree-sitter` crate, replacing the crates.io copy with my local checkout.

```
$ mkdir -p testing
$ git clone git clone git@github.com:tree-sitter/tree-sitter.git testing/tree-sitter

$ git diff Cargo.toml
diff --git i/Cargo.toml w/Cargo.toml
index 57e82c27d..5bef987fa 100644
--- i/Cargo.toml
+++ w/Cargo.toml
@@ -43,7 +43,7 @@ rustc-hash = "1.1.0"
 strsim = "0.10.0"
 lazy_static = "1.4.0"
 # tree-sitter 0.20.10 requires rust 1.65.
-tree-sitter = "0.20.9"
+tree-sitter = { path = "./testing/tree-sitter/lib" }
```

I then bisected the local copy of the `tree-sitter` crate. Here's the bisection replay log which seems to indicate that this is fixed by `67d13cf50b0b74f7037adec314a571bd68546ebf`:

```
$ git bisect log
git bisect start
# good: [2be51abcd8add3553c0ef389deff3732a630777d] Bump library versions
git bisect good 2be51abcd8add3553c0ef389deff3732a630777d
# bad: [811bc8256def2ddff65a1e46003263d7f49cd08e] lib: 0.20.10
git bisect bad 811bc8256def2ddff65a1e46003263d7f49cd08e
# bad: [19bd5868eb72ea3e72e29359a0f06056aa609140] Fix wasm tests
git bisect bad 19bd5868eb72ea3e72e29359a0f06056aa609140
# bad: [d07f864815ecb1e0f1f0bab17fec80438eb4c455] Fix parse error when reusing a node at the end of an included range
git bisect bad d07f864815ecb1e0f1f0bab17fec80438eb4c455
# bad: [cabdcfb41d780c760a2d0bea32f743b7d9ac8e4e] Merge pull request #1900 from gbprod/add-twig-parser
git bisect bad cabdcfb41d780c760a2d0bea32f743b7d9ac8e4e
# bad: [67d13cf50b0b74f7037adec314a571bd68546ebf] Fix integer size of subtree's child count field
git bisect bad 67d13cf50b0b74f7037adec314a571bd68546ebf
# good: [3563fe009aa3cf373ae01782979743e6aa258a0a] Explain in the docs that npm install supports limited platforms
git bisect good 3563fe009aa3cf373ae01782979743e6aa258a0a
# good: [d1d8193d2f71b3ef31f7f1d74a636093ff725586] Merge pull request #1858 from mattmassicotte/swift-docs-update
git bisect good d1d8193d2f71b3ef31f7f1d74a636093ff725586
# first bad commit: [67d13cf50b0b74f7037adec314a571bd68546ebf] Fix integer size of subtree's child count field
```

**Note**: Unfortunately, bumping the tree-sitter crate to `0.20.10` would also require the MSRV to be bumped because `0.20.10` seems to require `1.65` or newer, while `difftastic` currently specifies a MSRV of `1.63`.

I saw that you’ve filed a bug upstream already asking for the MSRV to be lowered maximally (such that the MSRV is truly a lower bound). By your criteria in that comment, you indicated wanting to support both:

1. the last 12 months of Rust versions
2. the current Debian stable

It seems like only one of those criteria is satisfied if there is a proposed bump to `1.65`:

1. Currently it is January 2024 and Rust `1.65.0` released on November 3, 2022 which is beyond the 12 month window
2. Debian stable seems to be tracking `1.63.0`, which is lower than the proposed `1.65.0` required for the new crate version

I can submit my changes to pull in the updated dependency, but I'm not sure if your stance has changed at all on the MSRV that `difftastic` supports since then?

**Comment by Wilfred** [comment] 2024-01-28 20:47
Thanks for the excellent investigation @karlding! So it's a tree-sitter bug, and not specific to the JSON parser.

I'd like to support Debian stable, but I think a bug like this is sufficiently important than I'm happy to increase the MSRV. The most important thing to me is that difftastic has a documented and tested MSRV.

This isn't the first time that I've had MSRV issues with dependencies. The Rust ecosystem seems to update MSRV pretty frequently, and there comes a point where my conservative MSRV is just making life hard.

**Comment by Wilfred** [comment] 2024-01-28 20:59
Upstream MSRV discussion: https://github.com/tree-sitter/tree-sitter/issues/2669

**Closed** 2024-01-28 21:12 UTC
Labels: upstream-parser
