### ISSUE TITLE
Difftastic incorrectly reports changed nullability in Kotlin as no syntactic change

### ISSUE THREAD

**Issue by mattiasflodin** [Wilfred/difftastic#589] opened 2023-10-26 07:44 UTC
Difftastic 0.52.0 on Ubuntu 22.04.3.

1. Create an empty git repository and add a Kotlin file named Foo.kt:
```kotlin
class Foo {
    val str: String?
}
```
2. Add and commit the file.
3. Remove the question mark, turning the String from nullable to non-nullable:
```kotlin
class Foo {
    val str: String
}
```
4. Run `git diff --no-ext-diff`. The diff shows:
```diff
--- a/Foo.kt
+++ b/Foo.kt
@@ -1,3 +1,3 @@
 class Foo {
-    val str: String?
+    val str: String
 }
```
5. Run `git diff` (with difftastic as external diff tool configured). The diff shows:
```
Foo.kt --- Kotlin
No syntactic changes.
```
I expected difftastic to show the removed question mark, as this is in fact both a syntactic and semantic change to the code.

**Comment by Wilfred** [comment] 2023-10-26 15:50
Thanks for the report. I'll add a workaround, but this is a dupe of #411 which needs upstream parser fixes.

**Closed by Wilfred** 2023-10-26 15:50 UTC
