### ISSUE TITLE
Rename `RUST_LOG` environment variable to avoid interference

### ISSUE THREAD

**Issue by nicholastmosher** [Wilfred/difftastic#628] opened 2024-01-29 17:41 UTC
> Thanks for reporting a bug! Please include all of the following:
>
> (1) A description of the issue. A screenshot is often helpful too.

As a developer writing primarily Rust, I often keep `RUST_LOG=info,...` defined in my environment. It would be great if `difft` used a custom environment variable (NOT `RUST_LOG`) to read the log filter level, so that it doesn't interfere when diffing inside a Rust project where `RUST_LOG` is always defined in the environment. `DIFFT_RUST_LOG` would be a great substitute, or perhaps adding a configuration key to explicitly name the environment variable would be the most flexible.

When I use `difftastic` via `git diff`, `difftastic`'s own log messages get activated. Here is a sample of what I see when I run `git diff`:

```
❯ git diff
 2024-01-29T17:31:43.861Z INFO  difft::options > CLI arguments: [".../src/lib.rs", "/var/folders/fp/xwd3fryx5qd5nnwbgl527vk00000gn/T//git-blob-BXJjdY/lib.rs", "6a0ceb33e9d35d81a23e5983b3681b99ed70ee8c", "100644", ".../src/lib.rs", "0000000000000000000000000000000000000000", "100644"]
 2024-01-29T17:31:43.884Z INFO  difft::diff::dijkstra > LHS nodes: 43 (9 toplevel), RHS nodes: 52 (10 toplevel)
 2024-01-29T17:31:43.884Z INFO  difft::diff::dijkstra > LHS nodes: 3 (3 toplevel), RHS nodes: 3 (3 toplevel)
 2024-01-29T17:31:43.884Z INFO  difft::diff::dijkstra > LHS nodes: 3 (3 toplevel), RHS nodes: 3 (3 toplevel)
 2024-01-29T17:31:43.884Z INFO  difft::diff::dijkstra > LHS nodes: 7 (7 toplevel), RHS nodes: 7 (7 toplevel)
 2024-01-29T17:31:43.884Z INFO  difft::diff::dijkstra > LHS nodes: 0 (0 toplevel), RHS nodes: 3 (1 toplevel)
 2024-01-29T17:31:43.884Z INFO  difft::diff::dijkstra > LHS nodes: 0 (0 toplevel), RHS nodes: 120 (1 toplevel)
.../src/lib.rs --- 1/3 --- Rust
24 24
25 25 use std::sync::Arc;
26 26
.. 27 use anyhow::{bail, Result};
```

This makes `difft` almost unusable when developing a Rust project. I'm happy to submit a PR to fix this if you agree and would be willing to merge the change, just let me know.

> (2) A copy of what you're diffing. If you're diffing files, include
> the before and after files. If you're using difftastic with a VCS
> repository (e.g. git), include the URL and commit hash.

N/A, this happens on all diffs

> (3) The version of difftastic you're using (see `difft --version`) and
> your operating system.

```
❯ difft --version
Difftastic 0.38.0
```

**Comment by Wilfred** [comment] 2024-01-29 22:21
Duplicate of #519, please upgrade :)

**Closed by Wilfred** 2024-01-29 22:21 UTC
