### ISSUE TITLE
[Feature]  Ignore changes by one character. Like comma "," or ";"

### ISSUE THREAD

**Issue by zodman** [Wilfred/difftastic#787] opened 2024-11-21 16:57 UTC
difft is soooo fucking awesome .... It is replacing my gitlab MR web version for review my code changes thanks for that.

it is possible by config ? 

something like  https://github.com/Wilfred/difftastic/issues/488

example:

```
function foo({ a, b }) {}



function foo({ a, b, }) {}


```

**Comment by Wilfred** [comment] 2024-12-23 23:54
Dupe of #419, thanks for the report!

**Closed by Wilfred** 2024-12-23 23:54 UTC
