### ISSUE TITLE
Wrong result for syntactically different python identation

### ISSUE THREAD

**Issue by ichianr** [Wilfred/difftastic#669] opened 2024-03-22 02:31 UTC
(1) A description of the issue. A screenshot is often helpful too.
Difftastic prints `No syntactic changes` for syntactically different python files.
![image](https://github.com/Wilfred/difftastic/assets/68317335/bee7fb91-f2de-48b0-a174-875eea11dfe3)

(2) A copy of what you're diffing. If you're diffing files, include the before and after files. If you're using difftastic with a VCS repository (e.g. git), include the URL and commit hash.
`a.py`:
```python
def f(args):
    if isinstance(args, list):
        print("hello")
    print("world")
```

`b.py`:
```python
def f(args):
    if isinstance(args, list):
        print("hello")
        print("world")
```

(3) The version of difftastic you're using (see `difft --version`) and your operating system.
```
$ difft --version
Difftastic 0.56.1 (d9d6401c4 2024-03-05, built with rustc 1.76.0)
```
It was installed with `pacman` in Arch Linux.

**Comment by LevitatingBusinessMan** [comment] 2024-03-22 16:22
> See also #657 and #637

Those issues are different from this one, as in this case the change _is_ syntactic.

**Comment by dirkfeytons** [comment] 2024-03-22 16:29
> > See also #657 and #637
> 
> Those issues are different from this one, as in this case the change _is_ syntactic.

I'm not saying they're the same; just that they're similar :)
Somebody looking to solve one of these issues might want to look at the other issues in case the cause and/or solution are related.

**Comment by Wilfred** [comment] 2024-03-22 22:40
Thanks for the report! This is a duplicate of #587, so closing in favour of that issue.

**Closed by Wilfred** 2024-03-22 22:40 UTC
