### ISSUE TITLE
Side-by-Side fallback displays very narrow columns

### ISSUE THREAD

**Issue by Rybadour** [Wilfred/difftastic#385] opened 2022-09-21 17:46 UTC
When I run Difftastic using git difftool inside a terminal in VSCode I get this output for side-by-side diffs:
![image](https://user-images.githubusercontent.com/305423/191573856-8e6499de-01e0-454e-9344-0c7680db7b7f.png)

The columns a quite small, they don't fill to fit the entire horizontal space available.

Before code:
```
<div rktStackItem class="rkt-BackgroundColor--gray-100">
</div>
```

After code (omitted some details for brevity):
```
<div rktStackItem class="rkt-BackgroundColor--gray-100 progressBar__section">
    <div class="progress-bar-container">
        <span>...</span>
        ...
    </div>
</div>
```

(2) A copy of what you're diffing. If you're diffing files, include
the before and after files. If you're using difftastic with a VCS
repository (e.g. git), include the URL and commit hash.

Difftastic version 0.35.0 on Windows 10.

**Comment by Wilfred** [comment] 2022-09-22 04:51
Duplicate of #363 I believe.

**Closed by Wilfred** 2022-09-22 04:51 UTC
